apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: rajatsinghal-3171075
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: rajatsinghal-3171075
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: rajatsinghal-3171075
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        namespace: rajatsinghal-3171075
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
